version: '3'

services:
  app:
    build: .
    command: npm run dev
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app

  postgres:
    container_name: 'postgres-node'
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
